# ==============================================================================
#  EMUBOX OS - DEFAULT EMULATOR ENGINE DEFINITIONS
# ==============================================================================

[snes]
default = snes9x
core = /usr/lib/libretro/snes9x_libretro.so
engine = retroarch

[ps1]
default = duckstation
engine = duckstation-qt
args = -batch -fullscreen

[ps2]
default = pcsx2
engine = pcsx2-qt
args = -fullscreen -batch

[n64]
default = mupen64plus
core = /usr/lib/libretro/mupen64plus_next_libretro.so
engine = retroarch

[genesis]
default = genesis_plus_gx
core = /usr/lib/libretro/genesis_plus_gx_libretro.so
engine = retroarch

[gba]
default = mgba
engine = mgba-qt
args = -f

[dreamcast]
default = flycast
engine = flycast
args = 

[arcade]
default = fbneo
core = /usr/lib/libretro/fbneo_libretro.so
engine = retroarch
